<?php

namespace Modules\Product\database\seeders;

use Illuminate\Database\Seeder;

class ProductVariationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_variations')->delete();
        
        \DB::table('product_variations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 1,
                'variation_key' => '1:1',
                'sku' => 'small',
                'code' => 'small',
                'price' => 20.0,
                'created_at' => '2023-09-20 12:18:47',
                'updated_at' => '2023-09-20 12:18:47',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 1,
                'variation_key' => '1:2',
                'sku' => 'mediam',
                'code' => 'mediam',
                'price' => 20.0,
                'created_at' => '2023-09-20 12:18:47',
                'updated_at' => '2023-09-20 12:18:47',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 1,
                'variation_key' => '1:3',
                'sku' => 'large',
                'code' => 'large',
                'price' => 20.0,
                'created_at' => '2023-09-20 12:18:47',
                'updated_at' => '2023-09-20 12:18:47',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'product_id' => 4,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 10.0,
                'created_at' => '2023-09-20 12:48:03',
                'updated_at' => '2023-09-20 12:48:03',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 15.0,
                'created_at' => '2023-09-20 12:48:03',
                'updated_at' => '2023-09-20 12:48:03',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'product_id' => 4,
                'variation_key' => '1:3',
                'sku' => 'Large',
                'code' => 'large',
                'price' => 25.0,
                'created_at' => '2023-09-20 12:48:03',
                'updated_at' => '2023-09-20 12:48:03',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'product_id' => 5,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 99.0,
                'created_at' => '2023-09-20 12:51:46',
                'updated_at' => '2023-09-20 12:51:46',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'product_id' => 5,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 199.0,
                'created_at' => '2023-09-20 12:51:46',
                'updated_at' => '2023-09-20 12:51:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'product_id' => 3,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 40.0,
                'created_at' => '2023-09-20 12:53:05',
                'updated_at' => '2023-09-20 12:53:05',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'product_id' => 3,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 55.0,
                'created_at' => '2023-09-20 12:53:05',
                'updated_at' => '2023-09-20 12:53:05',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'product_id' => 2,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 30.0,
                'created_at' => '2023-09-20 12:54:07',
                'updated_at' => '2023-09-20 12:54:07',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'product_id' => 2,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 50.0,
                'created_at' => '2023-09-20 12:54:07',
                'updated_at' => '2023-09-20 12:54:07',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'product_id' => 6,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 56.0,
                'created_at' => '2023-09-20 13:01:03',
                'updated_at' => '2023-09-20 13:01:03',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'product_id' => 6,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 56.0,
                'created_at' => '2023-09-20 13:01:04',
                'updated_at' => '2023-09-20 13:01:04',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'product_id' => 7,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 29.0,
                'created_at' => '2023-09-20 13:05:28',
                'updated_at' => '2023-09-20 13:05:28',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'product_id' => 7,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 39.0,
                'created_at' => '2023-09-20 13:05:28',
                'updated_at' => '2023-09-20 13:05:28',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'product_id' => 7,
                'variation_key' => '1:3',
                'sku' => 'Large',
                'code' => 'large',
                'price' => 59.0,
                'created_at' => '2023-09-20 13:05:28',
                'updated_at' => '2023-09-20 13:05:28',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'product_id' => 8,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 45.0,
                'created_at' => '2023-09-20 13:08:04',
                'updated_at' => '2023-09-20 13:08:04',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 21,
                'product_id' => 8,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 90.0,
                'created_at' => '2023-09-20 13:08:04',
                'updated_at' => '2023-09-20 13:08:04',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 22,
                'product_id' => 9,
                'variation_key' => NULL,
                'sku' => 'lamp1',
                'code' => 'lamp1',
                'price' => 100.0,
                'created_at' => '2023-09-20 13:12:56',
                'updated_at' => '2023-09-20 13:12:56',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 23,
                'product_id' => 10,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:12:32',
                'updated_at' => '2023-09-21 04:12:32',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 24,
                'product_id' => 10,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:12:32',
                'updated_at' => '2023-09-21 04:12:32',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 25,
                'product_id' => 10,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:12:32',
                'updated_at' => '2023-09-21 04:12:32',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 26,
                'product_id' => 11,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 59.0,
                'created_at' => '2023-09-21 04:15:34',
                'updated_at' => '2023-09-21 04:15:34',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 27,
                'product_id' => 11,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 59.0,
                'created_at' => '2023-09-21 04:15:34',
                'updated_at' => '2023-09-21 04:15:34',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 28,
                'product_id' => 11,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 59.0,
                'created_at' => '2023-09-21 04:15:34',
                'updated_at' => '2023-09-21 04:15:34',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'product_id' => 12,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 29.0,
                'created_at' => '2023-09-21 04:19:45',
                'updated_at' => '2023-09-21 04:19:45',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 30,
                'product_id' => 12,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 29.0,
                'created_at' => '2023-09-21 04:19:45',
                'updated_at' => '2023-09-21 04:19:45',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'product_id' => 12,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 29.0,
                'created_at' => '2023-09-21 04:19:45',
                'updated_at' => '2023-09-21 04:19:45',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'product_id' => 13,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 30.0,
                'created_at' => '2023-09-21 04:24:25',
                'updated_at' => '2023-09-21 04:24:25',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'product_id' => 13,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 30.0,
                'created_at' => '2023-09-21 04:24:25',
                'updated_at' => '2023-09-21 04:24:25',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 34,
                'product_id' => 13,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 30.0,
                'created_at' => '2023-09-21 04:24:25',
                'updated_at' => '2023-09-21 04:24:25',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 35,
                'product_id' => 14,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 38.0,
                'created_at' => '2023-09-21 04:30:15',
                'updated_at' => '2023-09-21 04:30:15',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 36,
                'product_id' => 14,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 38.0,
                'created_at' => '2023-09-21 04:30:15',
                'updated_at' => '2023-09-21 04:30:15',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 37,
                'product_id' => 14,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 38.0,
                'created_at' => '2023-09-21 04:30:15',
                'updated_at' => '2023-09-21 04:30:15',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 38,
                'product_id' => 15,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:34:30',
                'updated_at' => '2023-09-21 04:34:30',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 39,
                'product_id' => 15,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:34:30',
                'updated_at' => '2023-09-21 04:34:30',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 40,
                'product_id' => 15,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 70.0,
                'created_at' => '2023-09-21 04:34:30',
                'updated_at' => '2023-09-21 04:34:30',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 41,
                'product_id' => 16,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 86.0,
                'created_at' => '2023-09-21 04:38:04',
                'updated_at' => '2023-09-21 04:38:04',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 42,
                'product_id' => 16,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 86.0,
                'created_at' => '2023-09-21 04:38:04',
                'updated_at' => '2023-09-21 04:38:04',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 43,
                'product_id' => 16,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 86.0,
                'created_at' => '2023-09-21 04:38:04',
                'updated_at' => '2023-09-21 04:38:04',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 44,
                'product_id' => 17,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 90.0,
                'created_at' => '2023-09-21 04:42:26',
                'updated_at' => '2023-09-21 04:42:26',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 45,
                'product_id' => 17,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 90.0,
                'created_at' => '2023-09-21 04:42:26',
                'updated_at' => '2023-09-21 04:42:26',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 46,
                'product_id' => 17,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 90.0,
                'created_at' => '2023-09-21 04:42:26',
                'updated_at' => '2023-09-21 04:42:26',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 47,
                'product_id' => 18,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 42.0,
                'created_at' => '2023-09-21 04:49:33',
                'updated_at' => '2023-09-21 04:49:33',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 48,
                'product_id' => 18,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 42.0,
                'created_at' => '2023-09-21 04:49:33',
                'updated_at' => '2023-09-21 04:49:33',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 49,
                'product_id' => 18,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 42.0,
                'created_at' => '2023-09-21 04:49:33',
                'updated_at' => '2023-09-21 04:49:33',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 50,
                'product_id' => 19,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 50.0,
                'created_at' => '2023-09-21 04:55:36',
                'updated_at' => '2023-09-21 04:55:36',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 51,
                'product_id' => 19,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 50.0,
                'created_at' => '2023-09-21 04:55:36',
                'updated_at' => '2023-09-21 04:55:36',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 52,
                'product_id' => 19,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 50.0,
                'created_at' => '2023-09-21 04:55:36',
                'updated_at' => '2023-09-21 04:55:36',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 53,
                'product_id' => 20,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 41.0,
                'created_at' => '2023-09-21 04:58:37',
                'updated_at' => '2023-09-21 04:58:37',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 54,
                'product_id' => 20,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 41.0,
                'created_at' => '2023-09-21 04:58:37',
                'updated_at' => '2023-09-21 04:58:37',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 55,
                'product_id' => 20,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 41.0,
                'created_at' => '2023-09-21 04:58:37',
                'updated_at' => '2023-09-21 04:58:37',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 56,
                'product_id' => 21,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 53.0,
                'created_at' => '2023-09-21 05:46:10',
                'updated_at' => '2023-09-21 05:46:10',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 57,
                'product_id' => 21,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 53.0,
                'created_at' => '2023-09-21 05:46:10',
                'updated_at' => '2023-09-21 05:46:10',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 58,
                'product_id' => 21,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 53.0,
                'created_at' => '2023-09-21 05:46:10',
                'updated_at' => '2023-09-21 05:46:10',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 59,
                'product_id' => 22,
                'variation_key' => '1:2/2:4',
                'sku' => 'Mediam-Red',
                'code' => 'mediam-red',
                'price' => 36.0,
                'created_at' => '2023-09-21 05:56:23',
                'updated_at' => '2023-09-21 05:56:23',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 60,
                'product_id' => 22,
                'variation_key' => '1:2/2:5',
                'sku' => 'Mediam-Blue',
                'code' => 'mediam-blue',
                'price' => 36.0,
                'created_at' => '2023-09-21 05:56:23',
                'updated_at' => '2023-09-21 05:56:23',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 61,
                'product_id' => 22,
                'variation_key' => '1:2/2:6',
                'sku' => 'Mediam-Green',
                'code' => 'mediam-green',
                'price' => 36.0,
                'created_at' => '2023-09-21 05:56:23',
                'updated_at' => '2023-09-21 05:56:23',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 62,
                'product_id' => 23,
                'variation_key' => '1:2/2:5',
                'sku' => 'Mediam-Blue',
                'code' => 'mediam-blue',
                'price' => 56.0,
                'created_at' => '2023-09-21 06:07:37',
                'updated_at' => '2023-09-21 06:07:37',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 63,
                'product_id' => 23,
                'variation_key' => '1:2/2:6',
                'sku' => 'Mediam-Green',
                'code' => 'mediam-green',
                'price' => 56.0,
                'created_at' => '2023-09-21 06:07:37',
                'updated_at' => '2023-09-21 06:07:37',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 64,
                'product_id' => 23,
                'variation_key' => '1:3/2:5',
                'sku' => 'Large-Blue',
                'code' => 'large-blue',
                'price' => 56.0,
                'created_at' => '2023-09-21 06:07:37',
                'updated_at' => '2023-09-21 06:07:37',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 65,
                'product_id' => 23,
                'variation_key' => '1:3/2:6',
                'sku' => 'Large-Green',
                'code' => 'large-green',
                'price' => 56.0,
                'created_at' => '2023-09-21 06:07:37',
                'updated_at' => '2023-09-21 06:07:37',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 66,
                'product_id' => 24,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 52.0,
                'created_at' => '2023-09-21 06:22:50',
                'updated_at' => '2023-09-21 06:22:50',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 67,
                'product_id' => 24,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 52.0,
                'created_at' => '2023-09-21 06:22:50',
                'updated_at' => '2023-09-21 06:22:50',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 68,
                'product_id' => 24,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 52.0,
                'created_at' => '2023-09-21 06:22:50',
                'updated_at' => '2023-09-21 06:22:50',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 69,
                'product_id' => 25,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 25.0,
                'created_at' => '2023-09-21 06:29:32',
                'updated_at' => '2023-09-21 06:29:32',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 70,
                'product_id' => 25,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 25.0,
                'created_at' => '2023-09-21 06:29:32',
                'updated_at' => '2023-09-21 06:29:32',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 71,
                'product_id' => 25,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 25.0,
                'created_at' => '2023-09-21 06:29:32',
                'updated_at' => '2023-09-21 06:29:32',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 72,
                'product_id' => 26,
                'variation_key' => NULL,
                'sku' => 'toys1',
                'code' => 'toys1',
                'price' => 30.0,
                'created_at' => '2023-09-21 06:34:42',
                'updated_at' => '2023-09-21 06:34:42',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 73,
                'product_id' => 27,
                'variation_key' => NULL,
                'sku' => 'toy2',
                'code' => 'toy2',
                'price' => 52.0,
                'created_at' => '2023-09-21 06:39:34',
                'updated_at' => '2023-09-21 06:39:34',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 74,
                'product_id' => 28,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 63.0,
                'created_at' => '2023-09-21 06:44:13',
                'updated_at' => '2023-09-21 06:44:13',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 75,
                'product_id' => 28,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 63.0,
                'created_at' => '2023-09-21 06:44:13',
                'updated_at' => '2023-09-21 06:44:13',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 76,
                'product_id' => 28,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 63.0,
                'created_at' => '2023-09-21 06:46:06',
                'updated_at' => '2023-09-21 06:46:06',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 77,
                'product_id' => 29,
                'variation_key' => NULL,
                'sku' => 'toy3',
                'code' => 'toy3',
                'price' => 42.0,
                'created_at' => '2023-09-21 07:29:04',
                'updated_at' => '2023-09-21 07:29:04',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 78,
                'product_id' => 30,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 54.0,
                'created_at' => '2023-09-21 07:42:53',
                'updated_at' => '2023-09-21 07:42:53',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 79,
                'product_id' => 30,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 54.0,
                'created_at' => '2023-09-21 07:42:53',
                'updated_at' => '2023-09-21 07:42:53',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 80,
                'product_id' => 30,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 54.0,
                'created_at' => '2023-09-21 07:42:53',
                'updated_at' => '2023-09-21 07:42:53',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 81,
                'product_id' => 31,
                'variation_key' => NULL,
                'sku' => 'toy4',
                'code' => 'toy4',
                'price' => 56.0,
                'created_at' => '2023-09-21 07:45:46',
                'updated_at' => '2023-09-21 07:45:46',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 82,
                'product_id' => 32,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 50.0,
                'created_at' => '2023-09-21 07:49:31',
                'updated_at' => '2023-09-21 07:49:31',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 83,
                'product_id' => 32,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 50.0,
                'created_at' => '2023-09-21 07:49:31',
                'updated_at' => '2023-09-21 07:49:31',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 84,
                'product_id' => 32,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 50.0,
                'created_at' => '2023-09-21 07:49:31',
                'updated_at' => '2023-09-21 07:49:31',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 85,
                'product_id' => 33,
                'variation_key' => NULL,
                'sku' => 'toy5',
                'code' => 'tpy5',
                'price' => 45.0,
                'created_at' => '2023-09-21 08:12:38',
                'updated_at' => '2023-09-21 08:12:38',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 86,
                'product_id' => 34,
                'variation_key' => NULL,
                'sku' => 'toy6',
                'code' => 'toy6',
                'price' => 40.0,
                'created_at' => '2023-09-21 08:15:35',
                'updated_at' => '2023-09-21 08:15:35',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 87,
                'product_id' => 35,
                'variation_key' => '1:1/2:5',
                'sku' => 'Small-Blue',
                'code' => 'small-blue',
                'price' => 78.0,
                'created_at' => '2023-09-21 09:15:46',
                'updated_at' => '2023-09-21 09:15:46',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 88,
                'product_id' => 35,
                'variation_key' => '1:1/2:6',
                'sku' => 'Small-Green',
                'code' => 'small-green',
                'price' => 78.0,
                'created_at' => '2023-09-21 09:15:46',
                'updated_at' => '2023-09-21 09:15:46',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 89,
                'product_id' => 35,
                'variation_key' => '1:2/2:5',
                'sku' => 'Mediam-Blue',
                'code' => 'mediam-blue',
                'price' => 78.0,
                'created_at' => '2023-09-21 09:15:46',
                'updated_at' => '2023-09-21 09:15:46',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 90,
                'product_id' => 35,
                'variation_key' => '1:2/2:6',
                'sku' => 'Mediam-Green',
                'code' => 'mediam-green',
                'price' => 78.0,
                'created_at' => '2023-09-21 09:15:46',
                'updated_at' => '2023-09-21 09:15:46',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 91,
                'product_id' => 36,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 45.0,
                'created_at' => '2023-09-21 09:22:58',
                'updated_at' => '2023-09-21 09:22:58',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 92,
                'product_id' => 36,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 45.0,
                'created_at' => '2023-09-21 09:22:58',
                'updated_at' => '2023-09-21 09:22:58',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 93,
                'product_id' => 36,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 45.0,
                'created_at' => '2023-09-21 09:22:58',
                'updated_at' => '2023-09-21 09:22:58',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 94,
                'product_id' => 37,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 29.0,
                'created_at' => '2023-09-21 09:27:18',
                'updated_at' => '2023-09-21 09:27:18',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 95,
                'product_id' => 37,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 29.0,
                'created_at' => '2023-09-21 09:27:18',
                'updated_at' => '2023-09-21 09:27:18',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 96,
                'product_id' => 37,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 29.0,
                'created_at' => '2023-09-21 09:27:18',
                'updated_at' => '2023-09-21 09:27:18',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 97,
                'product_id' => 38,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 38.0,
                'created_at' => '2023-09-21 09:30:45',
                'updated_at' => '2023-09-21 09:30:45',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 98,
                'product_id' => 38,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 38.0,
                'created_at' => '2023-09-21 09:30:45',
                'updated_at' => '2023-09-21 09:30:45',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 99,
                'product_id' => 39,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 56.0,
                'created_at' => '2023-09-21 09:34:15',
                'updated_at' => '2023-09-21 09:34:15',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 100,
                'product_id' => 39,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 56.0,
                'created_at' => '2023-09-21 09:34:15',
                'updated_at' => '2023-09-21 09:34:15',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 101,
                'product_id' => 39,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 56.0,
                'created_at' => '2023-09-21 09:34:15',
                'updated_at' => '2023-09-21 09:34:15',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 102,
                'product_id' => 40,
                'variation_key' => '1:2/2:5',
                'sku' => 'Mediam-Blue',
                'code' => 'mediam-blue',
                'price' => 20.0,
                'created_at' => '2023-09-21 09:38:17',
                'updated_at' => '2023-09-21 09:38:17',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 103,
                'product_id' => 40,
                'variation_key' => '1:2/2:6',
                'sku' => 'Mediam-Green',
                'code' => 'mediam-green',
                'price' => 20.0,
                'created_at' => '2023-09-21 09:38:17',
                'updated_at' => '2023-09-21 09:38:17',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 104,
                'product_id' => 40,
                'variation_key' => '1:3/2:5',
                'sku' => 'Large-Blue',
                'code' => 'large-blue',
                'price' => 20.0,
                'created_at' => '2023-09-21 09:38:17',
                'updated_at' => '2023-09-21 09:38:17',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 105,
                'product_id' => 40,
                'variation_key' => '1:3/2:6',
                'sku' => 'Large-Green',
                'code' => 'large-green',
                'price' => 20.0,
                'created_at' => '2023-09-21 09:38:17',
                'updated_at' => '2023-09-21 09:38:17',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 106,
                'product_id' => 41,
                'variation_key' => NULL,
                'sku' => 'oral-strip',
                'code' => 'oral-strip',
                'price' => 36.0,
                'created_at' => '2023-09-21 09:43:23',
                'updated_at' => '2023-09-21 09:43:23',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 107,
                'product_id' => 42,
                'variation_key' => NULL,
                'sku' => 'vita-care',
                'code' => 'vita-care',
                'price' => 47.0,
                'created_at' => '2023-09-21 09:45:58',
                'updated_at' => '2023-09-21 09:45:58',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 108,
                'product_id' => 43,
                'variation_key' => NULL,
                'sku' => 'ultra-guard',
                'code' => 'ultra-guard',
                'price' => 19.0,
                'created_at' => '2023-09-21 09:48:46',
                'updated_at' => '2023-09-21 09:48:46',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 109,
                'product_id' => 44,
                'variation_key' => NULL,
                'sku' => 'dermspot',
                'code' => 'dermspot',
                'price' => 23.0,
                'created_at' => '2023-09-21 09:52:14',
                'updated_at' => '2023-09-21 09:52:14',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 110,
                'product_id' => 45,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 53.0,
                'created_at' => '2023-09-21 10:01:19',
                'updated_at' => '2023-09-21 10:01:19',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 111,
                'product_id' => 45,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 53.0,
                'created_at' => '2023-09-21 10:01:19',
                'updated_at' => '2023-09-21 10:01:19',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 112,
                'product_id' => 45,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 53.0,
                'created_at' => '2023-09-21 10:01:19',
                'updated_at' => '2023-09-21 10:01:19',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 113,
                'product_id' => 46,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 40.0,
                'created_at' => '2023-09-21 10:33:44',
                'updated_at' => '2023-09-21 10:33:44',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 114,
                'product_id' => 46,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 40.0,
                'created_at' => '2023-09-21 10:33:44',
                'updated_at' => '2023-09-21 10:33:44',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 115,
                'product_id' => 47,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 37.0,
                'created_at' => '2023-09-22 06:01:17',
                'updated_at' => '2023-09-22 06:01:17',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 116,
                'product_id' => 47,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 47.0,
                'created_at' => '2023-09-22 06:01:17',
                'updated_at' => '2023-09-22 06:01:17',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 117,
                'product_id' => 47,
                'variation_key' => '1:3',
                'sku' => 'Large',
                'code' => 'large',
                'price' => 57.0,
                'created_at' => '2023-09-22 06:01:17',
                'updated_at' => '2023-09-22 06:01:17',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 118,
                'product_id' => 48,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 25.0,
                'created_at' => '2023-09-22 06:05:24',
                'updated_at' => '2023-09-22 06:05:24',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 119,
                'product_id' => 48,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 35.0,
                'created_at' => '2023-09-22 06:05:24',
                'updated_at' => '2023-09-22 06:05:24',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 120,
                'product_id' => 49,
                'variation_key' => NULL,
                'sku' => 'jolly-good1',
                'code' => 'jolly-good1',
                'price' => 42.0,
                'created_at' => '2023-09-22 06:10:12',
                'updated_at' => '2023-09-22 06:10:12',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 121,
                'product_id' => 50,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 18.0,
                'created_at' => '2023-09-22 06:13:26',
                'updated_at' => '2023-09-22 06:13:26',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 122,
                'product_id' => 50,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 36.0,
                'created_at' => '2023-09-22 06:13:26',
                'updated_at' => '2023-09-22 06:13:26',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 123,
                'product_id' => 51,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 19.0,
                'created_at' => '2023-09-22 06:17:13',
                'updated_at' => '2023-09-22 06:17:13',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 124,
                'product_id' => 51,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 39.0,
                'created_at' => '2023-09-22 06:17:13',
                'updated_at' => '2023-09-22 06:17:13',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 125,
                'product_id' => 52,
                'variation_key' => NULL,
                'sku' => 'trixie1',
                'code' => 'trixie1',
                'price' => 58.0,
                'created_at' => '2023-09-22 06:19:40',
                'updated_at' => '2023-09-22 06:19:40',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 126,
                'product_id' => 53,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 46.0,
                'created_at' => '2023-09-22 06:22:26',
                'updated_at' => '2023-09-22 06:22:26',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 127,
                'product_id' => 53,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 46.0,
                'created_at' => '2023-09-22 06:22:26',
                'updated_at' => '2023-09-22 06:22:26',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 128,
                'product_id' => 53,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 46.0,
                'created_at' => '2023-09-22 06:22:26',
                'updated_at' => '2023-09-22 06:22:26',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 129,
                'product_id' => 54,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 12.0,
                'created_at' => '2023-09-22 06:26:59',
                'updated_at' => '2023-09-22 06:26:59',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 130,
                'product_id' => 54,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 23.0,
                'created_at' => '2023-09-22 06:26:59',
                'updated_at' => '2023-09-22 06:26:59',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 131,
                'product_id' => 55,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 15.0,
                'created_at' => '2023-09-22 06:35:59',
                'updated_at' => '2023-09-22 06:35:59',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 132,
                'product_id' => 55,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 32.0,
                'created_at' => '2023-09-22 06:35:59',
                'updated_at' => '2023-09-22 06:35:59',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 133,
                'product_id' => 55,
                'variation_key' => '1:3',
                'sku' => 'Large',
                'code' => 'large',
                'price' => 56.0,
                'created_at' => '2023-09-22 06:35:59',
                'updated_at' => '2023-09-22 06:35:59',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 134,
                'product_id' => 56,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 25.0,
                'created_at' => '2023-09-22 06:39:10',
                'updated_at' => '2023-09-22 06:39:10',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 135,
                'product_id' => 56,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 45.0,
                'created_at' => '2023-09-22 06:39:10',
                'updated_at' => '2023-09-22 06:39:10',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 136,
                'product_id' => 56,
                'variation_key' => '1:3',
                'sku' => 'Large',
                'code' => 'large',
                'price' => 69.0,
                'created_at' => '2023-09-22 06:39:10',
                'updated_at' => '2023-09-22 06:39:10',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 137,
                'product_id' => 57,
                'variation_key' => '1:1',
                'sku' => 'Small',
                'code' => 'small',
                'price' => 43.0,
                'created_at' => '2023-09-22 06:43:34',
                'updated_at' => '2023-09-22 06:43:34',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 138,
                'product_id' => 57,
                'variation_key' => '1:2',
                'sku' => 'Mediam',
                'code' => 'mediam',
                'price' => 85.0,
                'created_at' => '2023-09-22 06:43:34',
                'updated_at' => '2023-09-22 06:43:34',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 139,
                'product_id' => 58,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 48.0,
                'created_at' => '2023-09-22 06:46:20',
                'updated_at' => '2023-09-22 06:46:20',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 140,
                'product_id' => 58,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 48.0,
                'created_at' => '2023-09-22 06:46:20',
                'updated_at' => '2023-09-22 06:46:20',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 141,
                'product_id' => 58,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 48.0,
                'created_at' => '2023-09-22 06:46:20',
                'updated_at' => '2023-09-22 06:46:20',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 142,
                'product_id' => 59,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 15.0,
                'created_at' => '2023-09-22 06:50:26',
                'updated_at' => '2023-09-22 06:50:26',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 143,
                'product_id' => 59,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 15.0,
                'created_at' => '2023-09-22 06:50:26',
                'updated_at' => '2023-09-22 06:50:26',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 144,
                'product_id' => 59,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 15.0,
                'created_at' => '2023-09-22 06:50:26',
                'updated_at' => '2023-09-22 06:50:26',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 145,
                'product_id' => 60,
                'variation_key' => NULL,
                'sku' => 'trimmer1',
                'code' => 'trimmer1',
                'price' => 20.0,
                'created_at' => '2023-09-22 06:53:22',
                'updated_at' => '2023-09-22 06:53:22',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 146,
                'product_id' => 61,
                'variation_key' => NULL,
                'sku' => 'nail-clpper1',
                'code' => 'nail-clpper1',
                'price' => 59.0,
                'created_at' => '2023-09-22 06:56:35',
                'updated_at' => '2023-09-22 06:56:35',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 147,
                'product_id' => 62,
                'variation_key' => NULL,
                'sku' => 'purelab1',
                'code' => 'purelab1',
                'price' => 87.0,
                'created_at' => '2023-09-22 07:02:23',
                'updated_at' => '2023-09-22 07:02:23',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 148,
                'product_id' => 63,
                'variation_key' => NULL,
                'sku' => 'purelab2',
                'code' => 'purelab2',
                'price' => 58.0,
                'created_at' => '2023-09-22 07:05:05',
                'updated_at' => '2023-09-22 07:05:05',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 149,
                'product_id' => 64,
                'variation_key' => NULL,
                'sku' => 'pawfume1',
                'code' => 'pawfume1',
                'price' => 82.0,
                'created_at' => '2023-09-22 07:08:21',
                'updated_at' => '2023-09-22 07:08:21',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 150,
                'product_id' => 65,
                'variation_key' => NULL,
                'sku' => 'vvjoy1',
                'code' => 'vvjoy1',
                'price' => 42.0,
                'created_at' => '2023-09-22 07:10:57',
                'updated_at' => '2023-09-22 07:10:57',
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 151,
                'product_id' => 66,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 63.0,
                'created_at' => '2023-09-22 07:13:24',
                'updated_at' => '2023-09-22 07:13:24',
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 152,
                'product_id' => 66,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 63.0,
                'created_at' => '2023-09-22 07:13:24',
                'updated_at' => '2023-09-22 07:13:24',
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 153,
                'product_id' => 66,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 63.0,
                'created_at' => '2023-09-22 07:13:24',
                'updated_at' => '2023-09-22 07:13:24',
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 154,
                'product_id' => 67,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 98.0,
                'created_at' => '2023-09-22 07:18:47',
                'updated_at' => '2023-09-22 07:18:47',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 155,
                'product_id' => 67,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 98.0,
                'created_at' => '2023-09-22 07:18:47',
                'updated_at' => '2023-09-22 07:18:47',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 156,
                'product_id' => 67,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 98.0,
                'created_at' => '2023-09-22 07:18:47',
                'updated_at' => '2023-09-22 07:18:47',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 157,
                'product_id' => 68,
                'variation_key' => '2:4',
                'sku' => 'Red',
                'code' => 'red',
                'price' => 87.0,
                'created_at' => '2023-09-22 07:22:08',
                'updated_at' => '2023-09-22 07:22:08',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 158,
                'product_id' => 68,
                'variation_key' => '2:5',
                'sku' => 'Blue',
                'code' => 'blue',
                'price' => 87.0,
                'created_at' => '2023-09-22 07:22:08',
                'updated_at' => '2023-09-22 07:22:08',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 159,
                'product_id' => 68,
                'variation_key' => '2:6',
                'sku' => 'Green',
                'code' => 'green',
                'price' => 87.0,
                'created_at' => '2023-09-22 07:22:08',
                'updated_at' => '2023-09-22 07:22:08',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}