<?php

namespace Modules\Booking\database\seeders;

use Illuminate\Database\Seeder;

class BookingVeterinaryMappingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booking_veterinary_mapping')->delete();
        
        \DB::table('booking_veterinary_mapping')->insert(array (
            0 => 
            array (
                'id' => 1,
                'date_time' => '2023-08-01 11:30:00',
                'booking_id' => 10,
                'service_id' => 12,
                'service_name' => 'Tooth Extractions and Oral Surgeries',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:24:24',
                'updated_at' => '2023-08-01 13:24:24',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'date_time' => '2023-08-02 18:30:00',
                'booking_id' => 11,
                'service_id' => 4,
                'service_name' => 'Nutrition and diet counseling',
                'price' => 20.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:26:08',
                'updated_at' => '2023-08-01 13:26:08',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'date_time' => '2023-08-01 17:30:00',
                'booking_id' => 12,
                'service_id' => 6,
                'service_name' => 'Immediate Medical Attention For Serious Injuries or Illnesses',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:27:01',
                'updated_at' => '2023-08-01 13:27:01',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'date_time' => '2023-08-17 10:30:00',
                'booking_id' => 13,
                'service_id' => 16,
                'service_name' => 'Heart Health Assessment',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:28:27',
                'updated_at' => '2023-08-01 13:28:27',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'date_time' => '2023-08-30 18:50:00',
                'booking_id' => 14,
                'service_id' => 18,
                'service_name' => 'Diagnosis and Treatment of Neurological Disorders',
                'price' => 16.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:29:46',
                'updated_at' => '2023-08-01 13:29:46',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'date_time' => '2023-08-28 16:05:00',
                'booking_id' => 15,
                'service_id' => 12,
                'service_name' => 'Tooth Extractions and Oral Surgeries',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:30:39',
                'updated_at' => '2023-08-01 13:30:39',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'date_time' => '2023-08-03 10:10:00',
                'booking_id' => 16,
                'service_id' => 20,
                'service_name' => 'Breeding Management and Fertility Testing',
                'price' => 20.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:31:55',
                'updated_at' => '2023-08-01 13:31:55',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'date_time' => '2023-08-08 16:45:00',
                'booking_id' => 17,
                'service_id' => 22,
                'service_name' => 'X-rays and Ultrasounds for Diagnostic Purposes',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:32:42',
                'updated_at' => '2023-08-01 13:32:42',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'date_time' => '2023-08-04 11:05:00',
                'booking_id' => 18,
                'service_id' => 1,
                'service_name' => 'Routine check-ups and examinations',
                'price' => 12.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_at' => '2023-08-01 13:33:40',
                'updated_at' => '2023-08-01 13:33:40',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'date_time' => '2023-08-26 12:55:00',
                'booking_id' => 65,
                'service_id' => 9,
                'service_name' => 'Soft Tissue Surgery',
                'price' => 35.0,
                'duration' => 1,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 06:47:45',
                'updated_at' => '2023-08-26 06:47:45',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'date_time' => '2023-08-26 16:35:00',
                'booking_id' => 70,
                'service_id' => 5,
                'service_name' => '24/7 Emergency Services',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:05:57',
                'updated_at' => '2023-08-26 07:05:57',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'date_time' => '2023-08-26 13:25:00',
                'booking_id' => 71,
                'service_id' => 2,
                'service_name' => 'Vaccinations and preventive care',
                'price' => 10.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:12:14',
                'updated_at' => '2023-08-26 07:12:14',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'date_time' => '2023-08-29 19:40:00',
                'booking_id' => 72,
                'service_id' => 16,
                'service_name' => 'Heart Health Assessment',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:13:32',
                'updated_at' => '2023-08-26 07:13:32',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'date_time' => '2023-09-09 15:30:00',
                'booking_id' => 79,
                'service_id' => 12,
                'service_name' => 'Tooth Extractions and Oral Surgeries',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:26:02',
                'updated_at' => '2023-08-26 07:26:02',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'date_time' => '2023-08-26 18:30:00',
                'booking_id' => 81,
                'service_id' => 19,
                'service_name' => 'Seizure Management',
                'price' => 10.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:32:11',
                'updated_at' => '2023-08-26 07:32:11',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'date_time' => '2023-08-28 09:30:00',
                'booking_id' => 82,
                'service_id' => 14,
                'service_name' => 'Eye Examinations and Diagnostics',
                'price' => 25.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:32:58',
                'updated_at' => '2023-08-26 07:32:58',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'date_time' => '2023-08-27 16:25:00',
                'booking_id' => 84,
                'service_id' => 21,
                'service_name' => 'Pregnancy and Birthing Assistance',
                'price' => 35.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:34:53',
                'updated_at' => '2023-08-26 07:34:53',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'date_time' => '2023-08-29 10:15:00',
                'booking_id' => 85,
                'service_id' => 3,
                'service_name' => 'Parasite control and prevention',
                'price' => 16.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:36:02',
                'updated_at' => '2023-08-26 07:36:02',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'date_time' => '2023-08-28 11:25:00',
                'booking_id' => 86,
                'service_id' => 17,
                'service_name' => 'Diagnosis and Management of Heart Diseases',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:37:07',
                'updated_at' => '2023-08-26 07:37:07',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'date_time' => '2023-08-26 09:20:00',
                'booking_id' => 93,
                'service_id' => 10,
                'service_name' => 'Orthopedic Surgery',
                'price' => 40.0,
                'duration' => 1,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:51:29',
                'updated_at' => '2023-08-26 07:51:29',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'date_time' => '2023-08-26 19:25:00',
                'booking_id' => 94,
                'service_id' => 11,
                'service_name' => 'Dental Check Ups and Cleanings',
                'price' => 20.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:52:16',
                'updated_at' => '2023-08-26 07:52:16',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'date_time' => '2023-09-21 20:20:00',
                'booking_id' => 95,
                'service_id' => 13,
                'service_name' => 'Dental Disease Treatment and Prevention',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 07:55:25',
                'updated_at' => '2023-08-26 07:55:25',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'date_time' => '2023-09-12 15:35:00',
                'booking_id' => 101,
                'service_id' => 1,
                'service_name' => 'Routine check-ups and examinations',
                'price' => 12.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 08:58:20',
                'updated_at' => '2023-08-26 08:58:20',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'date_time' => '2023-09-05 10:25:00',
                'booking_id' => 102,
                'service_id' => 11,
                'service_name' => 'Dental Check Ups and Cleanings',
                'price' => 20.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 08:59:10',
                'updated_at' => '2023-08-26 08:59:10',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'date_time' => '2023-08-27 20:45:00',
                'booking_id' => 110,
                'service_id' => 8,
                'service_name' => 'Routine Spaying and Neutering',
                'price' => 23.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 09:27:37',
                'updated_at' => '2023-08-26 09:27:37',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'date_time' => '2023-09-02 18:30:00',
                'booking_id' => 116,
                'service_id' => 11,
                'service_name' => 'Dental Check Ups and Cleanings',
                'price' => 20.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 09:45:58',
                'updated_at' => '2023-08-26 09:45:58',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'date_time' => '2023-08-28 20:40:00',
                'booking_id' => 117,
                'service_id' => 13,
                'service_name' => 'Dental Disease Treatment and Prevention',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 09:48:39',
                'updated_at' => '2023-08-26 09:48:39',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'date_time' => '2023-08-28 19:20:00',
                'booking_id' => 123,
                'service_id' => 1,
                'service_name' => 'Routine check-ups and examinations',
                'price' => 12.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 10:06:28',
                'updated_at' => '2023-08-26 10:06:28',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'date_time' => '2023-09-13 16:30:00',
                'booking_id' => 129,
                'service_id' => 12,
                'service_name' => 'Tooth Extractions and Oral Surgeries',
                'price' => 30.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 10:21:08',
                'updated_at' => '2023-08-26 10:21:08',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'date_time' => '2023-08-26 18:30:00',
                'booking_id' => 134,
                'service_id' => 3,
                'service_name' => 'Parasite control and prevention',
                'price' => 16.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 10:31:44',
                'updated_at' => '2023-08-26 10:31:44',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'date_time' => '2023-09-05 11:30:00',
                'booking_id' => 141,
                'service_id' => 13,
                'service_name' => 'Dental Disease Treatment and Prevention',
                'price' => 40.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 10:50:16',
                'updated_at' => '2023-08-26 10:50:16',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'date_time' => '2023-08-26 06:35:00',
                'booking_id' => 146,
                'service_id' => 1,
                'service_name' => 'Routine check-ups and examinations',
                'price' => 12.0,
                'duration' => 0,
                'reason' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'start_video_link' => '',
                'join_video_link' => '',
                'created_at' => '2023-08-26 11:03:19',
                'updated_at' => '2023-08-26 11:03:19',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}